name: C++

on:
  push:
    branches: [ "main", "test/ci-cd" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  NYXSTONE_LLVM_PREFIX: "/usr/lib/llvm-15/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Packages
      run: sudo apt-get install llvm-15 llvm-15-dev zlib1g-dev libzstd-dev libboost-all-dev cppcheck clang-tidy clang-format
    - name: Code quality
      run: ./tool/format.sh check && ./tool/static-analysis-cppcheck.sh && ./tool/static-analysis-tidy.sh
    - name: Build
      run: mkdir build/ && cd build && cmake .. && make
    - name: Sample
      run: ./build/sample
    - name: cli
      run: ./build/nstone -A "mov rax, rbx"
