name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Packages
      run: apt install llvm15 llvm15-dev zlib1g-dev libzstd-dev
    - name: Prepare
      run: cd bindings/rust && make nyxstone
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose